language: php

php:
    - 5.3
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: 
    - phpunit --verbose
    - rm updater.php && phpunit --verbose
    
notifications:
    email:
        recipients:
            - b.pick@yellowtree.de
        on_success: change
        on_failure: always
