language: php

addons:
  code_climate:
    repo_token: 878c69a514f1dc1e54637e0f496c97752a0c5dfe76165bdd68d1e76eef1357d6

php:
    - 5.3
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

after_script:
  - vendor/bin/test-reporter

script: phpunit
