language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: 
    - phpunit --verbose
    
after_script:
  - export CODACY_PROJECT_TOKEN=3ecfa450a15ea817475cc34d631357f2
  - php vendor/bin/codacycoverage clover

notifications:
    email:
        recipients:
            - b.pick@yellowtree.de
        on_success: change
        on_failure: always
